### ISSUE TITLE
code

### ISSUE THREAD

**Issue by TigerandRosa** [lms-07/LGTEUN#1]
你好，我对你们的工作比较感兴趣，请问什么时候可以拜读一下源码？

**Comment by lms-07** [comment]
你好，感谢对我们工作关注。不出意外的话，我们尽量会在下周一之前realse一版比较完全的代码库。如果有需要可以持续关注一下。

**Comment by RXY66** [comment]
你好，我对你们的工作很感兴趣，请问什么时候可以拜读一下源码呢？

**Comment by lms-07** [comment]
你好，感谢对我们工作关注。我们尽量会在八月之前realse一版比较完全的代码库。

之前实在有事太忙，一直没有整理源码。

**Comment by TigerandRosa** [comment]
好的，感谢作者大大😌😌



---Original---
From: "Mingsong ***@***.***&gt;
Date: Thu, Jul 27, 2023 11:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lms-07/LGTEUN] code (Issue #1)




 
你好，感谢对我们工作关注。我们尽量会在八月之前realse一版比较完全的代码库。
 
之前实在有事太忙，一直没有整理源码。

**Comment by RXY66** [comment]
好的，谢谢

**Comment by lms-07** [comment]
大家好，我们的工作的基本代码库已经release，欢迎大家使用！

**Comment by TigerandRosa** [comment]
好的，收到，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lms-07/LGTEUN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月1日(星期二) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lms-07/LGTEUN] code (Issue #1)





 
大家好，我们的工作的基本代码库已经release，欢迎大家使用！

**Comment by RXY66** [comment]
收到，感谢
