### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by xuhonghui96** [lms-07/LGTEUN#2]
您好，我想问一下，代码里面的max_iter_list = [259000, 253000, 227500]是怎么计算的，因为论文里面写着epochs是1000

**Comment by lms-07** [comment]
感谢对工作关注，这个就是涉及给定data set训练集样本数量, epoch, iteration和设置batch size之间关系来确定的，您科研重点关注下。在我们工作中，我们对于两个四波段数据集是训练1000epochs。

**Comment by xuhonghui96** [comment]
您好，我想具体问一下这个计算公式是啥，因为我的epoch是300，我不知道如何去修改参数
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Nov 13, 2023 05:36 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [lms-07/LGTEUN] 参数问题 (Issue #2)

&nbsp;



 
感谢对工作关注，这个就是涉及给定data set训练集样本数量, epoch, iteration和设置batch size之间关系来确定的，您科研重点关注下。在我们工作中，我们对于两个四波段数据集是训练1000epochs。

**Comment by lms-07** [comment]
问题已解决
