### ISSUE TITLE
DataParallel

### ISSUE THREAD

**Issue by aleksmirosh** [lms-07/LGTEUN#4]
Hi guys, did you train it in parallel mode or distrubuted mode? I have a problem running it with DataParllel due to the error: 
`UserWarning: nn.ParameterList is being used with DataParallel but this is not supported. This list will appear empty for the models replicated on each GPU except the original one.`

**Comment by lms-07** [comment]
Hi bro,

Thanks for your interest in our work.

As mentioned in our paper, our experiments were run on a single 3090 GPU, thus, I have not trained it in a parallel mode with multiple GPUs.

Anyway, good luck!
